name: avalanche-authority

services:
  
  authority-gateway:
    image: avalanche/authority/gateway
    hostname: gateway.avalanche
    container_name: gateway
    restart: always
    ports:
      - "80:80"
    build:
      context: ../
      dockerfile: Avalanche.Gateway/Dockerfile
    networks:
      - authority
      
  authority-identity:
    image: avalanche/authority/identity
    hostname: identity.avalanche
    container_name: identity
    restart: always
    env_file: .env
    environment:
        Avalanche_Identity__ValidIssuers__2: "http://$AVALANCHE_PUBLIC_IP:5678/"
    ports:
      - "5678:5678"
    build:
      context: ../
      dockerfile: Avalanche.Identity.Api/Dockerfile
    networks:
      - authority
      - domain

networks:
  authority:
    name: avalanche-authority
    driver: bridge
  domain:
    name: avalanche-domain
    external: true