name: avalanche-services

services:
  
  business:
    image: avalanche/services/business
    hostname: business.avalanche
    container_name: business
    env_file: .env
    ports:
      - "80:8001"
    build:
      context: ../
      dockerfile: Avalanche.Business.Server/Dockerfile
    networks:
      - authority
      - domain
  
  inventory:
    image: avalanche/services/inventory
    hostname: inventory.avalanche
    container_name: inventory
    env_file: .env
    ports:
      - "80:8002"
    build:
      context: ../
      dockerfile: Avalanche.Inventory.Server/Dockerfile
    networks:
      - authority
      - domain

networks:
  authority:
    name: avalanche-authority
    external: true
  domain:
    name: avalanche-domain
    external: true